const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('index.html', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
const js = fs.readFileSync('script.js', 'utf8');
const gallerySection = html.match(/<section class="gallery[\s\S]*?<\/section>/)?.[0] || '';

assert.match(html, /data-gallery-preview/);
assert.match(html, /swiper-bundle\.min\.css/);
assert.match(html, /swiper-bundle\.min\.js/);
assert.match(html, /data-gallery-swiper="forward"/);
assert.match(html, /data-gallery-swiper="reverse"/);
assert.match(html, /class="swiper-wrapper"/);
assert.match(html, /data-gallery-toggle/);
assert.match(html, /aria-expanded="false"/);
assert.match(html, /id="gallery-grid"/);
assert.match(css, /gallery-preview[\s\S]*?100vw/);
assert.doesNotMatch(css, /\.gallery-preview\s*\{[^}]*background:\s*var\(--yellow\)/);
assert.match(css, /\.gallery-preview\s*\{[\s\S]*?overflow:\s*hidden/);
assert.doesNotMatch(css, /\.gallery-preview\s*\{[^}]*overflow-x:\s*auto/);
assert.match(css, /\.closing\s*\{[^}]*width:\s*100%/);
assert.match(css, /\.gallery-swiper\s*\{/);
assert.match(css, /\.gallery-swiper\s+\.swiper-wrapper\s*\{/);
assert.match(css, /\.gallery-preview\s*\{[\s\S]*?touch-action:\s*pan-y/);
assert.match(js, /new Swiper\(/);
assert.match(js, /loop:\s*true/);
assert.match(js, /allowTouchMove:\s*true/);
assert.match(js, /disableOnInteraction:\s*false/);
assert.match(js, /pauseOnMouseEnter:\s*false/);
assert.match(js, /swiper\.autoplay\.start\(\)/);
assert.match(js, /touchEnd/);
assert.doesNotMatch(js, /requestAnimationFrame/);
assert.doesNotMatch(js, /pointerdown/);
assert.doesNotMatch(js, /ResizeObserver/);
assert.doesNotMatch(js, /createGalleryLoop/);
assert.match(js, /const previewItems = galleryItems\.slice\(0,\s*32\)/);
assert.match(js, /index % 2 === 0/);
assert.match(js, /index % 2 === 1/);
assert.match(css, /prefers-reduced-motion:\s*reduce/);
assert.match(js, /gallery--expanded/);
assert.match(js, /aria-hidden/);
assert.match(js, /inert/);
assert.doesNotMatch(js, /image\.loading\s*=\s*['"]lazy['"]/);
assert.doesNotMatch(html, /<span class="gallery-caption">/);
assert.doesNotMatch(gallerySection, /<p class="section-description">/);
assert.doesNotMatch(gallerySection, /<img[^>]+alt="[^"]+"/);
assert.doesNotMatch(gallerySection, /registro/i);
assert.match(css, /\.gallery-grid\s*\{[\s\S]*?grid-auto-flow:\s*dense/);
assert.doesNotMatch(html, /^\+\s+<button class="gallery-item gallery-item--archive"/m);

console.log('gallery interaction contract checks passed');
