const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('index.html', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
const js = fs.readFileSync('script.js', 'utf8');
const gallerySection = html.match(/<section class="gallery[\s\S]*?<\/section>/)?.[0] || '';

assert.match(html, /data-gallery-preview/);
assert.match(html, /data-gallery-track="forward"/);
assert.match(html, /data-gallery-track="reverse"/);
assert.match(html, /data-gallery-toggle/);
assert.match(html, /aria-expanded="false"/);
assert.match(html, /id="gallery-grid"/);
assert.match(css, /gallery-preview[\s\S]*?100vw/);
assert.doesNotMatch(css, /\.gallery-preview\s*\{[^}]*background:\s*var\(--yellow\)/);
assert.match(css, /\.gallery-preview\s*\{[\s\S]*?overflow:\s*hidden/);
assert.doesNotMatch(css, /\.gallery-preview\s*\{[^}]*overflow-x:\s*auto/);
assert.match(css, /\.closing\s*\{[^}]*width:\s*100%/);
assert.match(css, /\.gallery-track\s*\{[\s\S]*?transform:\s*translate3d\(var\(--gallery-offset/);
assert.doesNotMatch(css, /@keyframes gallery-marquee/);
assert.match(css, /\.gallery-preview\s*\{[\s\S]*?touch-action:\s*pan-y/);
assert.match(js, /pointerdown/);
assert.match(js, /pointermove/);
assert.match(js, /pointerup/);
assert.match(js, /requestAnimationFrame/);
assert.match(js, /ResizeObserver/);
assert.match(js, /createGalleryLoop/);
assert.doesNotMatch(js, /enableGallerySwipe/);
assert.doesNotMatch(js, /gallery-drag-offset/);
assert.match(js, /const previewItems = galleryItems\.slice\(0,\s*16\)/);
assert.match(js, /index % 2 === 0/);
assert.match(js, /index % 2 === 1/);
assert.match(css, /prefers-reduced-motion:\s*reduce/);
assert.match(js, /gallery--expanded/);
assert.match(js, /aria-hidden/);
assert.match(js, /inert/);
assert.doesNotMatch(js, /image\.loading\s*=\s*['"]lazy['"]/);
assert.doesNotMatch(html, /<span class="gallery-caption">/);
assert.doesNotMatch(gallerySection, /<p class="section-description">/);
assert.doesNotMatch(gallerySection, /<img[^>]+alt="[^"]+"/);
assert.doesNotMatch(gallerySection, /registro/i);
assert.match(css, /\.gallery-grid\s*\{[\s\S]*?grid-auto-flow:\s*dense/);
assert.doesNotMatch(html, /^\+\s+<button class="gallery-item gallery-item--archive"/m);

console.log('gallery interaction contract checks passed');
